#!/usr/bin/env ruby

if ARGV.include?('--pygments') && `which pygmentize`.strip.empty?
  abort <<-END.gsub(/^ */, '')
    -------------------------------------------------------
    Please `easy_install Pygments` for syntax highlighting.
    -------------------------------------------------------
  END
end

exec 'jekyll', 'app', 'public', *ARGV
