#!/usr/bin/env ruby

if ARGV.include?('auto')
  # Since we're auto-reloading, we don't want pygments or lsi here
  exec 'script/jekyll', '--auto', '--server', '3000'
else
  require 'webrick'
  server = WEBrick::HTTPServer.new(:Port => 3000, :DocumentRoot => 'public')
  thread = Thread.new { server.start }
  trap('INT') { server.shutdown }
  thread.join
end
