#!/usr/bin/env ruby
# Since we're auto-reloading, we don't want pygments or lsi here
root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
exec "cd #{root}; bin/jekyll app public --auto --server 3000"
